name: Discord Notification on push

on:
  push:
    branches:
    - master

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: echo ${{ secrets }}
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master