name: Discord Notification on release created

on:
  page_build:
  release:
    types:
      - created

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new version has been released!'